# Q33 (VCL4THP), the missing direction: tournaments GENERATED BY bbpPairings
# itself (its own `-g` random tournament generator, `src/tournament/generator.cpp`),
# re-checked by Ainalrami - the reverse of the corpus in docs/validation.md,
# which is entirely Ainalrami-generated tournaments checked by bbpPairings.
#
# Methodology mirrors `Ainalrami.CLI`'s `-c` (Pairings Checker / FPC) path
# (`state_before_round/3` + `recorded_pairs/2` in lib/ainalrami/cli.ex, both
# private there) and the single-fixture proof in test/ainalrami/interop_test.exs
# ("replays every recorded round to the same pairing"), scaled up from one
# 209-player fixture to tens of thousands of independently generated
# tournaments.
#
# bbpPairings' generator (`tournament/generator.h`) picks, per seed:
#   PlayersNumber  15..215
#   RoundsNumber    5..15
#   ForfeitRate, RetiredRate, HalfPointByeRate, DrawPercentage
# writes NO round-count header and NO `152` (initial colour) - confirmed
# against test/fixtures/interop/README.md and by direct invocation. So:
#   * expected_rounds is taken from the file itself (max games length per
#     player), not guessed - the generator always plays out its full chosen
#     RoundsNumber against itself.
#   * initial_colour is never passed for round 2+, so
#     `Ainalrami.Pairing.pair_next_round/2` falls through to
#     `infer_initial_colour/1` exactly as it would for any real silent TRF -
#     a path the main 488M-pairing corpus (docs/validation.md) NEVER
#     exercises, because every comparison there states `initial_colour:`
#     explicitly (see bbppairings_comparison_test.exs's moduledoc).
#   * round 1 has nothing to infer from, so composition (who-plays-whom) is
#     the only thing compared there; colour is compared from round 2 on.
#
# Composition (who plays whom) is the headline "disagreement" number, same
# definition the 488M corpus uses. Colour is reported separately and never
# counted as a disagreement - Article 5.1 leaves the FIRST colour to a
# drawing of lots this file never recorded, so a colour difference that
# traces back to round 1 is a difference of convention, not of rule
# (same posture test/ainalrami/interop_test.exs already takes).
#
# Resumable: appends one line per completed tournament to RESULT_LOG
# (default tools/bbp_reverse_results.log) and skips any seed already logged,
# so a killed/restarted run picks up where it left off. Run with:
#
#   BBP_REVERSE_COUNT=50000 BBP_REVERSE_SEED_FROM=1 \
#     mix run tools/bbp_generator_reverse.exs
#
# Env:
#   BBPPAIRINGS_EXE      path to the binary (default: sibling OpenPairings checkout)
#   BBP_REVERSE_COUNT    how many NEW tournaments to attempt this invocation
#   BBP_REVERSE_SEED_FROM  first seed to try (default 1)
#   BBP_REVERSE_LOG      result log path (default tools/bbp_reverse_results.log)
#   BBP_REVERSE_DUMP     directory to dump composition mismatches (optional)

alias Ainalrami.{Pairing, Trf}

exe =
  System.get_env(
    "BBPPAIRINGS_EXE",
    "../openpairings/priv/bbppairings/bbpPairings-windows.exe"
  )

unless File.exists?(exe) do
  IO.puts(:stderr, "bbpPairings binary not found at #{exe} - set BBPPAIRINGS_EXE")
  System.halt(1)
end

count = String.to_integer(System.get_env("BBP_REVERSE_COUNT", "200"))
seed_from = String.to_integer(System.get_env("BBP_REVERSE_SEED_FROM", "1"))
log_path = System.get_env("BBP_REVERSE_LOG", "tools/bbp_reverse_results.log")
dump_dir = System.get_env("BBP_REVERSE_DUMP")

if dump_dir, do: File.mkdir_p!(dump_dir)

# ---------------------------------------------------------------------
# Resume support: a seed already present in the log is not repeated.
# ---------------------------------------------------------------------
already_done =
  if File.exists?(log_path) do
    log_path
    |> File.stream!()
    |> Stream.map(fn line ->
      case String.split(line, "\t") do
        [seed_str | _] -> String.to_integer(String.trim(seed_str))
        _ -> nil
      end
    end)
    |> Enum.reject(&is_nil/1)
    |> MapSet.new()
  else
    MapSet.new()
  end

log_file = File.open!(log_path, [:append, :utf8])

seeds_to_run =
  Stream.iterate(seed_from, &(&1 + 1))
  |> Stream.reject(&MapSet.member?(already_done, &1))
  |> Enum.take(count)

IO.puts(
  "Resuming: #{MapSet.size(already_done)} seed(s) already logged in #{log_path}. " <>
    "Running #{length(seeds_to_run)} new seed(s) (#{List.first(seeds_to_run)}..#{List.last(seeds_to_run)})."
)

# ---------------------------------------------------------------------
# One tournament: generate -> parse -> replay every round -> summarise.
# ---------------------------------------------------------------------
defmodule Reverse do
  alias Ainalrami.{Pairing, Trf}

  # bbpPairings' generator seeds a plain `std::minstd_rand` (a Park-Miller
  # LCG) with `-s`, and roundsNumber is the FIRST value drawn from it. Small
  # consecutive seeds correlate badly on an LCG's first draw: seeds 1..100
  # were measured to ALL produce roundsNumber == 5 (confirmed in a smoke
  # test - 20/20 - then confirmed again on scattered large seeds, which
  # spanned 4..14 rounds on the same 20 indices), which would make this
  # whole corpus a single, unrepresentative axis rather than the natural
  # 5..15-round spread the generator intends. Scattering the index through
  # a multiplicative hash before handing it to `-s` fixes that while
  # staying a deterministic, resumable function of the index - the log and
  # dump filenames key on the plain index, never on the hashed seed.
  def scatter_seed(i), do: rem(i * 2_654_435_761, 2_147_483_646) + 1

  def run(seed, exe) do
    dir =
      Path.join(
        System.tmp_dir!(),
        "ainalrami-bbprev-#{seed}-#{System.unique_integer([:positive])}"
      )

    File.mkdir_p!(dir)
    out = Path.join(dir, "gen.trf")
    bbp_seed = scatter_seed(seed)

    try do
      case System.cmd(exe, ["--dutch", "-g", "-o", out, "-s", to_string(bbp_seed)],
             stderr_to_stdout: true
           ) do
        {_, 0} ->
          text = File.read!(out)
          parsed = Trf.parse(text)
          measure(seed, parsed.players, text)

        {msg, code} ->
          %{seed: seed, generator_error: {code, String.slice(msg, 0, 300)}}
      end
    rescue
      e -> %{seed: seed, generator_error: {:raised, Exception.message(e)}}
    after
      File.rm_rf(dir)
    end
  end

  defp measure(seed, players, trf_text) do
    rounds = players |> Enum.map(&length(&1[:games] || [])) |> Enum.max(fn -> 0 end)

    if rounds == 0 or players == [] do
      %{seed: seed, empty: true}
    else
      per_round = Enum.map(1..rounds, &check_round(players, &1, rounds))

      errors = Enum.filter(per_round, & &1[:raised])
      ok = Enum.reject(per_round, & &1[:raised])

      %{
        seed: seed,
        players: length(players),
        rounds: rounds,
        rounds_compared: length(ok),
        rounds_raised: length(errors),
        pairs_matched: Enum.sum(Enum.map(ok, & &1.pairs_matched)),
        pairs_total: Enum.sum(Enum.map(ok, & &1.pairs_total)),
        composition_mismatches: Enum.count(ok, &(&1.pairs_matched != &1.pairs_total)),
        colour_shared: Enum.sum(Enum.map(ok, & &1.colour_shared)),
        colour_mismatches: Enum.sum(Enum.map(ok, & &1.colour_mismatches)),
        mismatch_rounds: for(r <- ok, r.pairs_matched != r.pairs_total, do: r.round),
        dump:
          if Enum.any?(ok, &(&1.pairs_matched != &1.pairs_total)) or errors != [] do
            trf_text
          else
            nil
          end
      }
    end
  end

  defp check_round(players, round, total_rounds) do
    before = state_before_round(players, round)
    actual = recorded_pairs(players, round)

    # Round 1: nothing to infer colour from, and nothing was stated by the
    # file either - pass an arbitrary initial_colour so pairing proceeds;
    # composition (who plays whom) never depends on it. Round 2+: no
    # initial_colour is passed at all, so `pair_next_round/2` infers it from
    # the (real, bbpPairings-produced) history it has just been handed.
    opts =
      if round == 1 do
        [expected_rounds: total_rounds, initial_colour: "w"]
      else
        [expected_rounds: total_rounds]
      end

    expected = Pairing.pair_next_round(before, opts)

    ours_norm = normalize(expected)
    theirs_norm = normalize(actual)

    matched = MapSet.size(MapSet.intersection(ours_norm, theirs_norm))
    total = MapSet.size(theirs_norm)

    {colour_mismatches, colour_shared} =
      if round == 1, do: {0, 0}, else: colour_diff(expected, actual)

    %{
      round: round,
      pairs_matched: matched,
      pairs_total: total,
      colour_mismatches: colour_mismatches,
      colour_shared: colour_shared,
      raised: false
    }
  rescue
    e ->
      %{
        round: round,
        pairs_matched: 0,
        pairs_total: length(recorded_pairs(players, round)),
        colour_mismatches: 0,
        colour_shared: 0,
        raised: {e.__struct__, Exception.message(e)}
      }
  end

  defp normalize(pairs) do
    MapSet.new(pairs, fn {w, b} -> if b, do: {min(w, b), max(w, b)}, else: {w, nil} end)
  end

  defp colour_diff(ours, theirs) do
    theirs_set = MapSet.new(theirs)

    reversed =
      Enum.count(ours, fn
        {_w, nil} -> false
        {w, b} -> MapSet.member?(theirs_set, {b, w}) and not MapSet.member?(theirs_set, {w, b})
      end)

    shared =
      Enum.count(ours, fn
        {_w, nil} -> false
        {w, b} -> MapSet.member?(theirs_set, {w, b}) or MapSet.member?(theirs_set, {b, w})
      end)

    {reversed, shared}
  end

  # Mirrors `Ainalrami.CLI`'s private `state_before_round/3` (lib/ainalrami/cli.ex) -
  # the tournament as it stood immediately before `round` was paired: every
  # earlier game, plus this round's own entry for anyone who did NOT
  # participate in the pairing (an arbiter-style bye recorded in advance).
  defp state_before_round(players, round) do
    Enum.map(players, fn player ->
      earlier = Enum.take(player.games, round - 1)

      games =
        case Enum.at(player.games, round - 1) do
          nil -> earlier
          game -> if Trf.participated_in_pairing?(game), do: earlier, else: earlier ++ [game]
        end

      %{
        player
        | games: games,
          points: Enum.sum(Enum.map(games, &Trf.points_for_game/1))
      }
    end)
  end

  # Mirrors `Ainalrami.CLI`'s private `recorded_pairs/2` - the pairing the
  # file records for `round`, as {white, black|nil}, each game claimed once
  # by its White.
  defp recorded_pairs(players, round) do
    Enum.flat_map(players, fn player ->
      case Enum.at(player.games, round - 1) do
        nil ->
          []

        game ->
          cond do
            not Trf.participated_in_pairing?(game) -> []
            is_nil(game.opponent_rank) -> [{player.rank, nil}]
            game.colour == "w" -> [{player.rank, game.opponent_rank}]
            game.colour == "b" -> []
            player.rank < game.opponent_rank -> [{player.rank, game.opponent_rank}]
            true -> []
          end
      end
    end)
  end
end

# ---------------------------------------------------------------------
# Drive it, streaming results to the log as they land (not batched at the
# end) so a killed run keeps everything completed so far.
# ---------------------------------------------------------------------
{:ok, agent} = Agent.start_link(fn -> %{done: 0, dumped: 0} end)

seeds_to_run
|> Task.async_stream(&Reverse.run(&1, exe),
  max_concurrency: System.schedulers_online(),
  timeout: :infinity,
  ordered: false
)
|> Stream.each(fn {:ok, r} ->
  seed = r.seed

  line =
    cond do
      r[:generator_error] ->
        "#{seed}\tgenerator_error\t#{inspect(r.generator_error)}\n"

      r[:empty] ->
        "#{seed}\tempty\n"

      true ->
        "#{seed}\tok\tplayers=#{r.players}\trounds=#{r.rounds}\t" <>
          "rounds_compared=#{r.rounds_compared}\trounds_raised=#{r.rounds_raised}\t" <>
          "pairs_matched=#{r.pairs_matched}\tpairs_total=#{r.pairs_total}\t" <>
          "composition_mismatches=#{r.composition_mismatches}\t" <>
          "colour_shared=#{r.colour_shared}\tcolour_mismatches=#{r.colour_mismatches}\t" <>
          "mismatch_rounds=#{inspect(r[:mismatch_rounds])}\n"
    end

  IO.write(log_file, line)

  if dump_dir && r[:dump] do
    File.write!(Path.join(dump_dir, "seed#{seed}.trf"), r.dump)
  end

  Agent.update(agent, fn s ->
    s = %{s | done: s.done + 1}
    if r[:dump], do: %{s | dumped: s.dumped + 1}, else: s
  end)

  if rem(Agent.get(agent, & &1.done), 200) == 0 do
    IO.puts("...#{Agent.get(agent, & &1.done)}/#{length(seeds_to_run)} done")
  end
end)
|> Stream.run()

File.close(log_file)
final = Agent.get(agent, & &1)

IO.puts(
  "Finished this invocation: #{final.done} tournament(s) processed, #{final.dumped} with a dump."
)
